python_tests(
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:moto',
    '3rdparty/python:mock',
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pantsbuild.pants.testinfra',
    'src/python/verst/pants/s3cache',
  ]
)
